services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
