services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    expose:
        - "9000"
        - "9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio_data:/data
  
  app:
    image: phonebook
    build: .
    ports:
      - 3003:3003
    depends_on:
      - db
    links:
      - db
    environment:
      - PORT=${PORT}
      - DATABASE_URL=postgres://postgres:example@db:5432/postgres
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

