name:                phonebook
version:             0.1.0.0
github:              "githubuser/phonebook"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/phonebook#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- aeson
- lens
- text
- time
- password
- bytestring
- utf8-string
- insert-ordered-containers
- postgresql-simple
- beam-core
- beam-postgres
- resource-pool
- servant
- servant-server
- servant-auth
- servant-auth-server
- string-conversions
- wai
- wai-logger
- warp
- http-types
- http-client
- http-media
- servant-openapi3
- servant-swagger-ui
- openapi3
- dotenv
- conduit
- servant-multipart
- minio-hs
- servant-multipart

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  phonebook-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - phonebook

tests:
  phonebook-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - phonebook
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
